#Passo a passo de fazer um Mijo(Marcarrao do cancer)
print("Separar panela com agua")
print("Colocar agua pra ferver")
print("Esperar chegar agua no ponto")
print("Abrir miolho")
print("Colocar projeto de macarrão na agua quente")
print("Esperar Miojo ficar molhe")
print("Colocar po")
print("misturar")
print("Colocar no prato")
print("comer")
